# Generated by Django 4.0.3 on 2022-04-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('6ᵗʰ', '6ᵗʰ'), ('7ᵗʰ', '7ᵗʰ'), ('8ᵗʰ', '8ᵗʰ'), ('9ᵗʰ', '9ᵗʰ'), ('10ᵗʰ', '10ᵗʰ')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_age', models.PositiveIntegerField()),
                ('stu_fathername', models.CharField(max_length=50)),
                ('stu_address', models.CharField(max_length=150)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author')),
            ],
        ),
    ]
