# Generated by Django 4.0.3 on 2022-05-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='def.png', upload_to='Profile_pics'),
        ),
    ]
